### ISSUE TITLE
Sound CH1 neu einsprechen

### ISSUE THREAD

**Issue by smeerws** [GameEwigkeitsaufgaben/Prototype#55]
general-talk-vNext
010160-talk-v01
010160-talk-v03
010160-talk-v07
010160-talk-v07a
010160-talk-v08
010160-talk-v10a
010160-talk-v15
010160-talk-v16
010160-talk-v18
010160-talk-v18a
010160-talk-g22
010160-talk-v23
010160-talk-v24
010160-talk-v27
010170-talk-g05

Aktuelle Liste der Gespräche im Google Drive im File Audio-Sound-Intern > AudioLernspielOV
Bitte aktualisierte audios wieder in den Audio-Sound-Intern > DummyAudiosLayout Ordner

**Comment by GruberWilfried** [comment]
Auf dem Drive hochgeladen und die alten Audios ersetzt
